# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "images/cache"
    loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.project_dir%/public/images/uploads/users/images"
                    - "%kernel.project_dir%/public/images/uploads/about_us"


    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    cache:                default
    data_loader:          default
    default_image:        null

    filter_sets:

        user_thumbnail:
            format: webp
            quality: 50
            filters:
                thumbnail:
                    size: [ 100, 100 ]
                    mode: outbound
