vich_uploader:
    metadata:
        type: attribute
    db_driver: orm

    mappings:
        image_about_us:
            uri_prefix: '%host%%app.path.image_about_us%'
            upload_destination: '%kernel.project_dir%/public%app.path.image_about_us%'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: vich_uploader.namer_uniqid

        image_users:
            uri_prefix: '%host%%app.path.image_users%'
            upload_destination: '%kernel.project_dir%/public%app.path.image_users%'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: vich_uploader.namer_uniqid

        image_user_small:
            uri_prefix: '%host%%app.path.image_users%'
            upload_destination: '%kernel.project_dir%/public%app.path.image_users%'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: vich_uploader.namer_uniqid
