vich_uploader:
    metadata:
        type: attribute
    db_driver: orm

    mappings:
        image_about_us:
            uri_prefix: '%host%%app.path.image_about_us%'
            upload_destination: '%kernel.project_dir%/public%app.path.image_about_us%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer:
                service: App\VichUploader\ImageNamer
                options: { property: 'name', extension: 'webp' }

        image_user:
            uri_prefix: '%host%%app.path.image_users%'
            upload_destination: '%kernel.project_dir%/public%app.path.image_users%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer:
                service: App\VichUploader\ImageNamer
                options: { property: 'name', extension: 'webp' }

        attachment_file:
            uri_prefix: /api/attachments/file
            upload_destination: '%kernel.project_dir%/storage/attachments'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
